spring:
  tomcat:
    port: 8080
  profiles.active: local
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
base-url: "http://localhost:${spring.tomcat.port}/" #Base url will of web server from which you want provide redirection.
